// <auto-generated />
using System;
using Booking_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Marcoff_API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedsOcuppied")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            BedsOcuppied = 3,
                            DateCreated = new DateTime(2024, 3, 1, 16, 37, 44, 493, DateTimeKind.Local).AddTicks(6394),
                            DateModified = new DateTime(2024, 3, 1, 16, 37, 44, 493, DateTimeKind.Local).AddTicks(6412),
                            Detail = "Abonó 10%",
                            Fee = 200.0,
                            Name = "Ricardo"
                        },
                        new
                        {
                            Id = 4,
                            BedsOcuppied = 4,
                            DateCreated = new DateTime(2024, 3, 1, 16, 37, 44, 493, DateTimeKind.Local).AddTicks(6416),
                            DateModified = new DateTime(2024, 3, 1, 16, 37, 44, 493, DateTimeKind.Local).AddTicks(6417),
                            Detail = "Abonó 10%",
                            Fee = 150.0,
                            Name = "Romualdo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
